var chEnText = {
  "mywallet":{
    "ch":{
      "walletAddress":"當前綁定錢包地址：",
      "rechargeDataNull":"無法獲取充值信息",
      "httpError":"網絡錯誤，無法獲取賬戶信息",
      "deleteSuc":"删除成功",
      "connectWallet":"請連接錢包",
      "balanceInsufficient":"餘額不足",
      "amountWithdrawal":"請填寫提現金額",
      "apppleWithdrawal":"提款申請已收到，請等待",
      "withdrawalsErr":"提款失敗",
      "hintMessage01":"您的賬戶綁定地址與當前錢包地址不符，點擊確定會為您綁定當前錢包地址\n當前錢包地址: ",
      "hintMessage02":" \n賬戶綁定地址: ",
      "binded":"當前錢包已被綁定占有, 請更換錢包防止誤充",
      "emailNot":"郵箱未驗證",
      "loginNot":"登錄已失效，請重新登錄",
      "windowErr":"系統錯誤",
      "startTopUp":"充值已發起,期間請勿更換錢包防止誤充",
      "rechargeSuc":"充值已成功"
    },
    "en":{
      "walletAddress":"當前綁定錢包地址：",
      "rechargeDataNull":"無法獲取充值信息",
      "httpError":"網絡錯誤，無法獲取賬戶信息",
      "deleteSuc":"删除成功",
      "connectWallet":"請連接錢包",
      "balanceInsufficient":"餘額不足",
      "amountWithdrawal":"請填寫提現金額",
      "apppleWithdrawal":"提款申請已收到，請等待",
      "withdrawalsErr":"提款失敗",
      "hintMessage01":"您的賬戶綁定地址與當前錢包地址不符，點擊確定會為您綁定當前錢包地址\n當前錢包地址: ",
      "hintMessage02":" \n賬戶綁定地址: ",
      "binded":"當前錢包已被綁定占有, 請更換錢包防止誤充",
      "emailNot":"郵箱未驗證",
      "loginNot":"登錄已失效，請重新登錄",
      "windowErr":"系統錯誤",
      "startTopUp":"充值已發起,期間請勿更換錢包防止誤充",
      "rechargeSuc":"充值已成功"
    }
  },
  "myOrders":{
    "ch":{
      "myWallt":"去我的資產核對",
      "confirm":"確認",
      "cancel":"取消",
      "noResults":"暫無搜索結果",
      "buyDate":"購買日期：",
      "number":"訂單號 # ",
      "purchased":"已購第",
      "version01":"版，共",
      "version02":"版",
      "paymentMethod":"支付方式：",
      "cryptocurrencies":"加密貨幣",
      "price":"單價：",
      "purchasePrice":"購買價格 : ",
      "bankCard":"銀行卡支付",
      "balanceInsufficient":"餘額不足",
      "paySuc":"支付成功",
      "payErr":"支付失敗",
      "cardAuthorization":"您的信用卡將被立即授權",
      "recharge":"充值",
      "payment":"立即付款",
      "walletImpower":"您的錢包將立即得到授權",
      "accomplis":"完成",
      "toAssets":"去我的資產核對",
      "balancePayment":"餘額支付"
    },
    "en":{
      "myWallt":"去我的資產核對",
      "confirm":"確認",
      "cancel":"取消",
      "noResults":"暫無搜索結果",
      "buyDate":"購買日期：",
      "number":"訂單號 # ",
      "purchased":"已購第",
      "version01":"版，共",
      "version02":"版",
      "paymentMethod":"支付方式：",
      "cryptocurrencies":"加密貨幣",
      "price":"單價：",
      "purchasePrice":"購買價格 : ",
      "bankCard":"銀行卡支付",
      "balanceInsufficient":"餘額不足",
      "paySuc":"支付成功",
      "payErr":"支付失敗",
      "cardAuthorization":"您的信用卡將被立即授權",
      "recharge":"充值",
      "payment":"立即付款",
      "walletImpower":"您的錢包將立即得到授權",
      "accomplis":"完成",
      "toAssets":"去我的資產核對",
      "balancePayment":"餘額支付"
    }
  },
  "artwork":{
    "ch":{
      "noResult":"暫無搜索結果",
      "xdd":"徐冬冬 牛N.X潮玩 NFT限量版",
      "sellOut":"已售罄",
      "purchaseNow":"立即購買",
      "salesClosed":"銷售已結束"
    },
    "en":{
      "noResult":"暫無搜索結果",
      "xdd":"徐冬冬 牛N.X潮玩 NFT限量版",
      "sellOut":"已售罄",
      "purchaseNow":"立即購買",
      "salesClosed":"銷售已結束"
    }
  },
  "auction":{
    "ch":{
      "haveBid":"我的出價",
      "bid":"報價不能低於初始出價",
      "startingPrice":"拍賣開始時間：",
      "endPrice":"拍賣剩餘時間：",
      "auctionEnd":"競標結束",
      "topPrice":"恭喜！ 您是出價最高者！",
      "assetLook":"去我的資產查看",
      "bidFailure":"您上次競標失敗",
      "lose":"未登入/錢包連接已失效",
      "notBegun":"拍賣未開始",
      "msg01":"請先安裝MetaMask/或者使用WalletConnect，以保證拍賣功能的使用",
      "msg02":"轉到MetaMask的網站",
      "address01":"當前連接錢包地址為：",
      "address02":"當前頁面的競拍記錄以當前連接的錢包為準，如果您使用了其他錢包參與競拍，可以切換至其他錢包查看競拍記錄。",
      "walletLose":"錢包連接已失效，請重新連接錢包"
    },
    "en":{
      "haveBid":"我的出價",
      "bid":"報價不能低於初始出價",
      "startingPrice":"拍賣開始時間：",
      "endPrice":"拍賣剩餘時間：",
      "auctionEnd":"競標結束",
      "topPrice":"恭喜！ 您是出價最高者！",
      "assetLook":"去我的資產查看",
      "bidFailure":"您上次競標失敗",
      "lose":"未登入/錢包連接已失效",
      "notBegun":"拍賣未開始",
      "msg01":"請先安裝MetaMask/或者使用WalletConnect，以保證拍賣功能的使用",
      "msg02":"轉到MetaMask的網站",
      "address01":"當前連接錢包地址為：",
      "address02":"當前頁面的競拍記錄以當前連接的錢包為準，如果您使用了其他錢包參與競拍，可以切換至其他錢包查看競拍記錄。",
      "walletLose":"錢包連接已失效，請重新連接錢包"
    }
  },
  "auctionPayment":{
    "ch":{
      "walletLose":"錢包連接已失效，請重新連接錢包",
      "hintMessage0101":"您的賬戶未綁定地址，點擊確定會為您自動綁定當前錢包地址\n基於區塊鏈的獨立性，即使不綁定您仍然可以參與競拍\n當前錢包地址: ",
      "hintMessage0102":" \n賬戶綁定地址: null",
      "hintMessage0201":"您的賬戶綁定地址與當前錢包地址不符，點擊確定會為您重新綁定當前錢包地址\n基於區塊鏈的獨立性，即使不綁定您仍然可以參與競拍\n當前錢包地址: ",
      "hintMessage0202":" \n賬戶綁定地址: ",
      "bindSuc":"綁定成功！",
      "bindErr":"綁定失敗！",
      "noLogin":"您尚未登錄，無法綁定錢包，但基於區塊鏈的獨立性，您仍然可以參與競拍\n當前錢包地址: ",
      "priceSuc":"競價成功",
      "priceErr":"競價失敗！",
      "accomplish":"完成",
      "youPriceSuc":"您的競標成功。",
      "number":"訂單號：",
      "youPrice":"您的競標價格為",
      "payAddress":"付費地址："
    },
    "en":{
      "walletLose":"錢包連接已失效，請重新連接錢包",
      "hintMessage0101":"您的賬戶未綁定地址，點擊確定會為您自動綁定當前錢包地址\n基於區塊鏈的獨立性，即使不綁定您仍然可以參與競拍\n當前錢包地址: ",
      "hintMessage0102":" \n賬戶綁定地址: null",
      "hintMessage0201":"您的賬戶綁定地址與當前錢包地址不符，點擊確定會為您重新綁定當前錢包地址\n基於區塊鏈的獨立性，即使不綁定您仍然可以參與競拍\n當前錢包地址: ",
      "hintMessage0202":" \n賬戶綁定地址: ",
      "bindSuc":"綁定成功！",
      "bindErr":"綁定失敗！",
      "noLogin":"您尚未登錄，無法綁定錢包，但基於區塊鏈的獨立性，您仍然可以參與競拍\n當前錢包地址: ",
      "priceSuc":"競價成功",
      "priceErr":"競價失敗！",
      "accomplish":"完成",
      "youPriceSuc":"您的競標成功。",
      "number":"訂單號：",
      "youPrice":"您的競標價格為",
      "payAddress":"付費地址："
    } 
  },
  "common":{
    "ch":{
      "logOutMes":"你確定要登出嗎",
      "suc":"成功",
      "cancel":"取消",
      "myaccount":"我的帳戶",
      "myorders":"我的訂單",
      "myassets":"我的資產",
      "mywallet":"我的錢包",
      "logOut":"登出",
      "login":"登入/註冊",
      "connectWallet":"已連接錢包",
      "noConnectWallet":"未連接錢包"
    },
    "en":{
      "logOutMes":"你確定要登出嗎",
      "suc":"成功",
      "cancel":"取消",
      "myaccount":"我的帳戶",
      "myorders":"我的訂單",
      "myassets":"我的資產",
      "mywallet":"我的錢包",
      "logOut":"登出",
      "login":"登入/註冊",
      "connectWallet":"已連接錢包",
      "noConnectWallet":"未連接錢包"
    }
  },
  "connectWallet":{
    "ch":{
      "logWtllet":"您成功登記了一個錢包",
      "connectWallet":"請連接錢包",
      "walletAddress":"錢包地址：",
      "tips01":"請註意：您購買的NFT資產只會發放至當前登記的錢包",
      "tips02":"（ 如果您想使用其他錢包，請點擊右上角“已連接錢包”進行更換 ）",
      "know":"知道了",
      "changeWallet":"該錢包已被綁定占有, 請更換錢包",
      "emailErr":"郵箱未驗證",
      "loginNot":"登錄已失效，請重新登錄",
      "windowErr":"系統錯誤",
      "httpError":"網絡錯誤，無法獲取賬戶信息",
      "unableGet":"無法獲取錢包信息",
      "alert":"請使用任意錢包Dapp中自帶的瀏覽器訪問 bazhuayu.io，則可成功連接錢包。或請使用電腦，通過瀏覽器的錢包插件連接錢包。"
    },
    "en":{
      "logWtllet":"您成功登記了一個錢包",
      "connectWallet":"請連接錢包",
      "walletAddress":"錢包地址：",
      "tips01":"請註意：您購買的NFT資產只會發放至當前登記的錢包",
      "tips02":"（ 如果您想使用其他錢包，請點擊右上角“已連接錢包”進行更換 ）",
      "know":"知道了",
      "changeWallet":"該錢包已被綁定占有, 請更換錢包",
      "emailErr":"郵箱未驗證",
      "loginNot":"登錄已失效，請重新登錄",
      "windowErr":"系統錯誤",
      "httpError":"網絡錯誤，無法獲取賬戶信息",
      "unableGet":"無法獲取錢包信息",
      "alert":"請使用任意錢包Dapp中自帶的瀏覽器訪問 bazhuayu.io，則可成功連接錢包。或請使用電腦，通過瀏覽器的錢包插件連接錢包。"
    }
  },
  "forgotPassword":{
    "ch":{
      "verificationCode":"驗證已發送到郵箱",
      "emailErr":"驗證已發送到郵箱"
    },
    "en":{
      "verificationCode":"驗證已發送到郵箱",
      "emailErr":"驗證已發送到郵箱"
    } 
  },
  "frames":{
    "ch":{
      "number":"卡號",
      "validCardNumber":"請輸入有效的卡號",
      "validDate":"請輸入有效的到期日期",
      "validCvv":"請輸入有效的cvv程式碼"
    },
    "en":{
      "number":"卡號",
      "validCardNumber":"請輸入有效的卡號",
      "validDate":"請輸入有效的到期日期",
      "validCvv":"請輸入有效的cvv程式碼"
    }
  },
  "function":{
    "ch":{
      "passWord":"密碼至少8位，請至少包含一個大寫字母和一個小寫字母",
      "recharge":"充值",
      "nowRecharge":"立即充值",
      "connectWallet":"請連接錢包",
      "amount":"輸入金額",
      "withdraw":"提款",
      "nowWithdraw":"立即提款",
      "changeCard":"更換信用卡",
      "deleteData":"刪除資料",
      "deleteCard":"您確定要刪除信用卡信息嗎？不能撤消。",
      "delete":"刪除",
      "deleteWallt":"您確定要刪除錢包信息嗎？不能撤消。",
      "chengeNick":"更換暱稱",
      "currentNick":"當前暱稱：",
      "newNick":"輸入新暱稱",
      "save":"儲存",
      "changeNFT":"修改BSC NFT接收地址",
      "currentAddress":"當前接收地址：",
      "noAddress":"暫無接收地址",
      "newAddress":"新接收地址：",
      "tips01":"提示：一旦鑄造完成，則不可修改地址。如需查看該NFT，需連接新接收地址才可查看",
      "edit":"確認修改",
      "transfer":"轉移Token",
      "newWallt":"至新錢包",
      "walltAdress":"當前所在錢包地址：",
      "transferTo":"轉移至：",
      "tips02":"提示：轉移至新錢包后，需連接新錢包才可在“我的NFT”中查看",
      "confirmCurrent":"確認轉移",
      "changePassword":"更換密碼",
      "currentPassword":"當前密碼",
      "enterCurrentPassword":"輸入當前密碼",
      "currentPasswordErr":"當前密碼不正確。",
      "newPassword":"新密碼",
      "entweNewPassword":"輸入新密碼",
      "passwordLength":"密碼長度不少於6比特",
      "passwordReg":"密碼至少8位，請至少包含一個大寫字母和一個小寫字母",
      "repeatPassword":"重複新密碼",
      "repeatPasswordErr":"重複密碼不正確",
      "noConnectWallet":"未連接錢包",
      "noLog":"未登錄，請登入"
    },
    "en":{
      "passWord":"密碼至少8位，請至少包含一個大寫字母和一個小寫字母",
      "recharge":"充值",
      "nowRecharge":"立即充值",
      "connectWallet":"請連接錢包",
      "amount":"輸入金額",
      "withdraw":"提款",
      "nowWithdraw":"立即提款",
      "changeCard":"更換信用卡",
      "deleteData":"刪除資料",
      "deleteCard":"您確定要刪除信用卡信息嗎？不能撤消。",
      "delete":"刪除",
      "deleteWallt":"您確定要刪除錢包信息嗎？不能撤消。",
      "chengeNick":"更換暱稱",
      "currentNick":"當前暱稱：",
      "newNick":"輸入新暱稱",
      "save":"儲存",
      "changeNFT":"修改BSC NFT接收地址",
      "currentAddress":"當前接收地址：",
      "noAddress":"暫無接收地址",
      "newAddress":"新接收地址：",
      "tips01":"提示：一旦鑄造完成，則不可修改地址。如需查看該NFT，需連接新接收地址才可查看",
      "edit":"確認修改",
      "transfer":"轉移Token",
      "newWallt":"至新錢包",
      "walltAdress":"當前所在錢包地址：",
      "transferTo":"轉移至：",
      "tips02":"提示：轉移至新錢包后，需連接新錢包才可在“我的NFT”中查看",
      "confirmCurrent":"確認轉移",
      "changePassword":"更換密碼",
      "currentPassword":"當前密碼",
      "enterCurrentPassword":"輸入當前密碼",
      "currentPasswordErr":"當前密碼不正確。",
      "newPassword":"新密碼",
      "entweNewPassword":"輸入新密碼",
      "passwordLength":"密碼長度不少於6比特",
      "passwordReg":"密碼至少8位，請至少包含一個大寫字母和一個小寫字母",
      "repeatPassword":"重複新密碼",
      "repeatPasswordErr":"重複密碼不正確",
      "noConnectWallet":"未連接錢包",
      "noLog":"未登錄，請登入"
    }
  },
  "login":{
    "ch":{
      "emailMgs":"該郵箱已被注册，但未驗證，去驗證郵箱",
      "confirm":"確認",
      "cancel":"取消",
      "logSuc":"登入成功",
      "logErr":"郵箱或密碼錯誤",
      "dataErr":"郵箱或密碼不能為空"
    },
    "en":{
      "emailMgs":"The mailbox has been registered but not verified. Please verify the mailbox",
      "confirm":"Confirmation",
      "cancel":"cancel",
      "logSuc":"Login successful",
      "logErr":"Email or password error",
      "dataErr":"Email or password cannot be empty"
    }
  },
  "myaccount":{
    "ch":{
      "nick":"當前暱稱：",
      "nickUnNull":"昵稱不能為空",
      "editSuc":"修改成功"
    },
    "en":{
      "nick":"當前暱稱：",
      "nickUnNull":"昵稱不能為空",
      "editSuc":"修改成功"
    }
  },
  "myassets":{
    "ch":{
      "tables":["我的藏品","我的NFT","NFT操作記錄"]
    },
    "en":{
      "tables":["我的藏品","我的NFT","NFT操作記錄"]
    }
  },
  "mywalletCard":{
    "ch":{
      "number":"卡號",
      "validCardNumber":"請輸入有效的卡號",
      "validDate":"請輸入有效的到期日期",
      "validCvv":"請輸入有效的cvv程式碼"
    },
    "en":{
      "number":"卡號",
      "validCardNumber":"請輸入有效的卡號",
      "validDate":"請輸入有效的到期日期",
      "validCvv":"請輸入有效的cvv程式碼"
    } 
  },
  "reset":{
    "ch":{
      "tips01":"密碼不能為空",
      "tips02":"密碼長度不能低於8",
      "tips03":"兩次密碼不相等",
      "tips04":"修改成功"
    },
    "en":{
      "tips01":"密碼不能為空",
      "tips02":"密碼長度不能低於8",
      "tips03":"兩次密碼不相等",
      "tips04":"修改成功"
    }
  },
  "showwallet":{
    "ch":{
      "bindWallt":"當前綁定錢包地址如下：",
      "NFTWallt":"當前購買的所有NFT資產將會默認發送至以上錢包地址",
      "change":"更換",
      "delete":"刪除",
      "cancel":"取消",
      "deleteSuc":"删除成功"
    },
    "en":{
      "bindWallt":"當前綁定錢包地址如下：",
      "NFTWallt":"當前購買的所有NFT資產將會默認發送至以上錢包地址",
      "change":"更換",
      "delete":"刪除",
      "cancel":"取消",
      "deleteSuc":"删除成功"
    }
  },
  "signup":{
    "ch":{
      "verificationEmail":"去驗證郵箱",
      "suc":"成功",
      "cancel":"取消",
      "tips01":"密码请输入一致",
      "tips02":"該郵箱已被注册，但未驗證",
      "tips03":"該郵箱已被注册，請嘗試換一個郵箱",
      "tips04":"當前禁止註冊",
      "tips05":"郵箱格式不正確"
    },
    "en":{
      "verificationEmail":"去驗證郵箱",
      "suc":"成功",
      "cancel":"取消",
      "tips01":"密码请输入一致",
      "tips02":"該郵箱已被注册，但未驗證",
      "tips03":"該郵箱已被注册，請嘗試換一個郵箱",
      "tips04":"當前禁止註冊",
      "tips05":"郵箱格式不正確"
    }
  },
  "upload":{
    "ch":{
      "tips01":"您拖的不是图片！",
      "tips02":"上传大小不能超过2M."
    },
    "en":{
      "tips01":"您拖的不是图片！",
      "tips02":"上传大小不能超过2M."
    }
  },
  "verificationCode":{
    "ch":{
      "tips01":"發送成功",
      "tips02":"注册成功"
    },
    "en":{
      "tips01":"發送成功",
      "tips02":"注册成功"
    }
  }
}

